### ISSUE TITLE
Downgrade to Scala 3.3.x LTS

### ISSUE THREAD

**Issue by majk-p** [kovstas/fs2-throttler#115]
Hi @kovstas 
First of all thanks for a great library!
I noticed that in release [v1.0.10](https://github.com/kovstas/fs2-throttler/releases/tag/v1.0.10) there is a change by Scala Steward to update to Scala 3.4.1. For libraries, it's recommended to stick with 3.3.x LTS line. Quoting the release announcement:
https://www.scala-lang.org/blog/2024/02/29/scala-3.4.0-and-3.3.3-released.html#-so-which-version-should-i-update-to

> Scala 3.4.0 code can use dependencies compiled with Scala 3.3.x, but not the other way around

How do you feel about downgrading to LTS and sticking to it?

**Comment by kovstas** [comment]
Hi Sure, it's good idea to stick with the LTS version. Thank you for your help! 
I'll release a new version soon

**Comment by majk-p** [comment]
Great, thank you!
